### ISSUE TITLE
UUID.randomUUID() is detected as blocking, any replacement?

### ISSUE THREAD

**Issue by AtticusLv** [reactor/BlockHound#157]
hi, I use blockhound in Env: Spring Cloud Gateway, the scenario is that each response need to generate to UUID, I use UUID.randomUUID(), but the Blockhound is warning it is blocking call! Any good suggestion is appreciated!
Thanks

Stack trace:
		at java.io.FileInputStream.readBytes(FileInputStream.java)
		at java.io.FileInputStream.read(FileInputStream.java:255)
		at sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424)
		at sun.security.provider.NativePRNG$RandomIO.ensureBufferValid(NativePRNG.java:525)
		at sun.security.provider.NativePRNG$RandomIO.implNextBytes(NativePRNG.java:544)
		at sun.security.provider.NativePRNG$RandomIO.access$400(NativePRNG.java:331)
		at sun.security.provider.NativePRNG.engineNextBytes(NativePRNG.java:220)
		at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
		at java.util.UUID.randomUUID(UUID.java:145)

**Comment by bsideup** [comment]
`UUID.randomUUID()` _is_ a blocking call.

Either use a non-blocking id generator, move it to a blocking friendly scheduler, or [ignore it by allowing blocking calls inside](https://github.com/reactor/BlockHound/blob/master/docs/customization.md#dis-allowing-blocking-calls-inside-methods)

**Comment by AtticusLv** [comment]
@bsideup thanks for the answer. Do you have any suggestion for the non-blocking uuid generator?
or
Is it a friendly way to use UUID.randomUUID() in non-blocking process, such as below codes:

```
Mono uuidMono = Mono.fromCallable(() -> UUID.randomUUID().toString())
                .subscribeOn(Schedulers.boundedElastic())
return uuidMono.flapMap(uuid -> {
    // TODO
    // return sth using uuid;
}
)
```

**Comment by persicsb** [comment]
@AtticusLv ```UUID:randomUUID()``` is a blocking call, beacuse per its specification, it must draw a random number from a cryptographically secure random source. And those sources are often tied to the outside world (like harware elements, user interactions etc.) and thus are blocking. 

You may want to use other UUIDs (there are a couple of types), for example a t ime-based UUID.  See Section 4.2 of https://www.ietf.org/rfc/rfc4122.txt

**Comment by AtticusLv** [comment]
https://github.com/apache/openwhisk/issues/2747
