### ISSUE TITLE
Blocking call detected even when subscribed to Schedulers.boundedElastic()

### ISSUE THREAD

**Issue by theakshaypilania** [reactor/BlockHound#160]
### Overview
We are planning to migrate our blocking Spring boot micro-service to a non-blocking IO Spring Webflux. During testing of our demo service, we used a blocking client(Jedis) to retrieve data from Redis but it was subscribed to Schedulers.elastic(), but still blockhound detected it as a blocking call

## Expected Behavior

Because it was a normal thread pool(elastic), hence the blocking service shouldn't have been recognized as a blocking call.
## Actual Behavior

Block hound detecting it as a blocking call. Stack trace:
```
2020-12-08 15:07:44,140 INFO  [main] o.s.b.w.e.n.NettyWebServer:109:[, ] - Netty started on port(s): 8080
2020-12-08 15:07:44,156 INFO  [main] c.m.d.DdReactiveApplication:61:[, ] - Started DdReactiveApplication in 5.037 seconds (JVM running for 5.735)
2020-12-08 15:07:50,809 ERROR [reactor-http-epoll-3] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler:122:[, ] - [aa0d19ef-1]  500 Server Error for HTTP GET "/getPolicyObj?key=a"
reactor.blockhound.BlockingOperationError: Blocking call! java.net.SocketOutputStream#socketWrite0
	at java.net.SocketOutputStream.socketWrite0(SocketOutputStream.java)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ HTTP GET "/getPolicyObj?key=a" [ExceptionHandlingWebHandler]
Stack trace:
		at java.net.SocketOutputStream.socketWrite0(SocketOutputStream.java)
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
		at redis.clients.jedis.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:52)
		at redis.clients.jedis.util.RedisOutputStream.flush(RedisOutputStream.java:133)
		at redis.clients.jedis.Connection.flush(Connection.java:265)
		at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:214)
		at redis.clients.jedis.Connection.getBulkReply(Connection.java:205)
		at redis.clients.jedis.Jedis.get(Jedis.java:185)
		at redis.clients.jedis.JedisCluster$3.execute(JedisCluster.java:198)
		at redis.clients.jedis.JedisCluster$3.execute(JedisCluster.java:195)
		at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:106)
		at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:25)
		at redis.clients.jedis.JedisCluster.get(JedisCluster.java:200)
		at com.mmt.ddreactive.CacheUtil.get(CacheUtil.java:60)
		at com.mmt.ddreactive.service.DDService.getPolicyObjFromCacheFromJedis(DDService.java:123)
		at com.mmt.ddreactive.controller.DDController.getPolicyObj(DDController.java:88)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:146)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784)
		at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251)
		at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336)
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:99)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2346)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2154)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2028)
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
		at reactor.core.publisher.Mono.subscribe(Mono.java:3972)
		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:154)
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:281)
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:860)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2346)
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2154)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2028)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152)
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
		at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:448)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:218)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:173)
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:611)
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:612)
		at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:453)
		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:510)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:185)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)

```
## Steps to Reproduce

Calling this backend service function, here cacheUtil.get() is a blocking call to jedis.get(), but as it is subscribed to boundedElastic, it shouldn't be a blocking call.
```java
public Mono<String> getPolicyObjFromCacheFromJedis(String key) {
    return Mono.just(cacheUtil.get(key)).subscribeOn(Schedulers.boundedElastic()).log();
  }
```

## Possible Solution

NA

## Your Environment

* Reactor version(s) used: 
3.4.0
* Other relevant libraries versions (eg. `netty`, ...):
Netty version: 4.1.54.Final
* JVM version (`javar -version`):
Oracle JDK
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
* OS and version (eg `uname -a`):
Linux mmt-ubt-8341 5.4.0-53-generic #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Jedis version: 3.3.0
* Blockhound version : 1.0.4.RELEASE

**Comment by simonbasle** [comment]
`Mono.just` has an intrinsic immediate nature, because it is just a method call with a parameter.
Since you produce this parameter with another method call (`cacheUtil.get(key)`), that method is immediately invoked by _java_, irrespective of whether or not you've appended `subscribeOn` in the chain.

Switch from `just` to `Mono.fromCallable(() -> cacheUtil.get(key))` and it will actually defer the call to `cacheUtil` and be able to offload it to the scheduler you specify via `subscribeOn`.

**Comment by theakshaypilania** [comment]
Thank you for sharing knowledge, new to reactive programming. Hope you can understand. :)

**Comment by simonbasle** [comment]
This is one of the most common beginner's mistakes, no worries @theakshaypilania 😉 
The correct recipe I exposed above is actually described in the FAQ of the Reference Guide [here](https://projectreactor.io/docs/core/snapshot/reference/#faq.wrap-blocking). I would strongly encourage you to read all of the reference guide if you haven't already 👍
