### ISSUE TITLE
NoClassDefFoundError with Java 11

### ISSUE THREAD

**Issue by garyrussell** [reactor/BlockHound#196]
This app, when run with Java8 reproduces https://github.com/reactor/reactor-kafka/issues/215 (fixed by [this PR](https://github.com/reactor/reactor-kafka/pull/216)).

[rkgh215.zip](https://github.com/reactor/BlockHound/files/6358639/rkgh215.zip)

When run with Java 11 (`./mvnw spring-boot:run `), however, it fails with:

```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.kafka.common.utils.AppInfoParser
	at org.apache.kafka.common.requests.ApiVersionsRequest$Builder.<clinit>(ApiVersionsRequest.java:38) ~[kafka-clients-2.6.1.jar:na]
	at org.apache.kafka.clients.NetworkClient.handleConnections(NetworkClient.java:910) ~[kafka-clients-2.6.1.jar:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:555) ~[kafka-clients-2.6.1.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:325) ~[kafka-clients-2.6.1.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:240) ~[kafka-clients-2.6.1.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by garyrussell** [comment]
Strangely, this problem goes away when I compile/run with the snapshot containing the above reference PR.

Feel free to close this if you don't think it warrants investigation.

**Comment by bsideup** [comment]
@garyrussell `AppInfoParser` has this code:
```java
static {
        Properties props = new Properties();
        try (InputStream resourceStream = AppInfoParser.class.getResourceAsStream("/kafka/kafka-version.properties")) {
            props.load(resourceStream);
        } catch (Exception e) {
            log.warn("Error while loading kafka-version.properties: {}", e.getMessage());
        }
        VERSION = props.getProperty("version", DEFAULT_VALUE).trim();
        COMMIT_ID = props.getProperty("commitId", DEFAULT_VALUE).trim();
    }
```

it is indeed blocking, so BlockHound barks and the classloading fails (as the static blocks are executed at the classloading time)

**Comment by garyrussell** [comment]
Ah - thanks; understood; since the constructor is now called on the other thread (with my r-k PR), we're good.

Closing this.

**Comment by Abdulkhakimov** [comment]
Hi @garyrussell . Looks like the issue has been occured again in recent versions.
`2023-02-14 14:57:56,239 [,]  ERROR [ ws-user-client] o.a.k.c.u.KafkaThread                   : Uncaught exception in thread 'kafka-producer-network-thread | ws-user-client':
java.lang.NoClassDefFoundError: Could not initialize class org.apache.kafka.common.utils.AppInfoParser
	at org.apache.kafka.common.requests.ApiVersionsRequest$Builder.<clinit>(ApiVersionsRequest.java:37)
	at org.apache.kafka.clients.NetworkClient.handleConnections(NetworkClient.java:950)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:73)
	at org.apache.kafka.clients.producer.internals.Sender.awaitNodeReady(Sender.java:526)
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:447)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by garyrussell** [comment]
@Abdulkhakimov Try calling `AppInfoParser.getVersion()` on the main thread before starting any reactive workloads; that should initialize the static.

**Comment by Abdulkhakimov** [comment]
@garyrussell It all worked without any barking from BlockHound. Very grateful for the help!
