### ISSUE TITLE
java.lang.UnsatisfiedLinkError: reactor.blockhound.BlockHoundRuntime.isBlocking()Z

### ISSUE THREAD

**Issue by szpak** [reactor/BlockHound#39]
Trying to add my own "blocking" method in the JMH tests I've encountered:
```
java.lang.UnsatisfiedLinkError: reactor.blockhound.BlockHoundRuntime.isBlocking()Z

	at reactor.blockhound.BlockHoundRuntime.isBlocking(Native Method)
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:42)
	at com.example.Blocking.block(Blocking.java)
	at com.example.Grrr2Test.shouldAllowToDefineCustomBlockingMethod(Grrr2Test.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```
(execution of JUnit test (next to already existing `com.example` tests) from Idea).

To a builder configuration I add `builder.markAsBlocking(Blocking.class, "block", "()V");` and call that method in JUnit test (or JMH test).

There could be a problem with a visibility of that class by the agent, but in that case the problem will also arise in real-life usage with own blocking methods. However, probably not too many projects will be affected (adding extra blocking methods from Java classes works - unless they are final - then they are silently ignored).

**Comment by bsideup** [comment]
Hi @szpak,

I finally managed to fix it! Thanks for reporting 👍
See #40 for the details
